### ISSUE TITLE
failed on ./bin/startup

### ISSUE THREAD

**Issue by renankruger** [EYBlockchain/starlight#206]
Hey guys,

any idea why am I receiving this error?

 => ERROR [escrow-timber internal] load git source  https://github.com/EYBlockchain/timber.git#starlight/testnet:merkle-tree                            
 0.0s
------
 > [escrow-timber internal] load git source https://github.com/EYBlockchain/timber.git#starlight/testnet:merkle-tree:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: failed to load cache key: subdir not supported yet

**Comment by renankruger** [comment]
probably I need to run on a arm processor?
#platform: linux/arm64/v8

**Comment by SwatiEY** [comment]
Hi..
Don't use builkit. Try these commands and I think it will work
`export DOCKER_BUILDKIT=0`
`export COMPOSE_DOCKER_CLI_BUILD=0`

**Comment by renankruger** [comment]
Tks
