### ISSUE TITLE
What happens to a proof of a failed transaction?

### ISSUE THREAD

**Issue by renankruger** [EYBlockchain/starlight#210]
http: Zokrates responded to the generateProof request 
 {
  proof: {
    a: [
      '0x0044f65842f455e520a4dd6f1b908e6b61fdb80f8033694feda4dd2bf8c3496f',
      '0x08082c338f08e8e704d043a8ee9e91e9809d220b5e71631fd87949d677a9ffa4'
    ],
    b: [
      [
        '0x0f2e8ea52a9759844856fdec5b7eedff22a0cefcc776257a9756e615b641b0b8',
        '0x267fbae2cf940de8b68ce52ba2a5c9287bcb796ee371ea2fb80ccac4aecae80a'
      ],
      [
        '0x0ef1a79a0c5d936aea1c6b147f7d00d8bc14297e63e0a9233a0c6ee06321e4d5',
        '0x0bf382729c1560afbbf63dc365ed10baeb067dc1a32460307b5eb8ae393f2252'
      ]
    ],
    c: [
      '0x1b9f6b72205937f3c2ae67e0871c9ce346bd9101d663e4edbd7650abbefd7749',
      '0x00b916a043d17af0742cc0ef59ccb54936976e09e48d8d3738e2dd5a3f12ad0d'
    ]
  },
  inputs: [
    '0x2f68a1c58e257e42a17a6c61dff5551ed560b9922ab119d5ac8e184c9734ead9',
    '0x2b14aefe2edacb5449ff5a3de92697d5166407bcd86d79c2b30f0bbe8c4abe50',
    '0x20f2707ca961275b85084d6ef8bae730865b25f424c6d212b3c87641f1af47e0',
    '0x2ae3ad1937680a3cb458ba438f151bb30405d0ebe1b5b800bfc755ae074347da',
    '0x0c5d31b6a1cac50108b2c1b7e039d90a36685bdd34afbbfd4bc65b9fbbf625bb',
    '0x1b2f9e45688412401e67fcb08b26f22840f304a91434702b126a457eb4e6e42d',
    '0x26c146cf285f285710b78cd8fc9a1cb0e2e209da677ed899c1f7f1438499bebc',
    '0x0000000000000000000000000000000000000000000000000000000000000001'
  ],
  type: 'transfer'
}
error: Returned error: insufficient funds for gas * price + value Error: Returned error: insufficient funds for gas * price + value
    at Object.ErrorResponse (/app/node_modules/web3-core-requestmanager/node_modules/web3-core-helpers/lib/errors.js:28:19)
    at Object.callback (/app/node_modules/web3-core-requestmanager/lib/index.js:300:36)
    at /app/node_modules/web3-providers-ws/lib/index.js:114:45

Whenever the transaction fails would the state of the Merkle tree be changed?

**Comment by MirandaWood** [comment]
Hi, no nothing at all happens. No state is changed because no transaction went through. Hope that helps!

**Comment by renankruger** [comment]
tks
