### ISSUE TITLE
Escrow.zol zapp transfers are not working well.

### ISSUE THREAD

**Issue by renankruger** [EYBlockchain/starlight#212]
Hey guys, I was able to make two deposits on the Escrow shield contract, but whenever I try to transfer or withdraw the result is a failed transaction like this one:

https://mumbai.polygonscan.com/tx/0xe305942bca6db60f2497bb94a7c55071037c6cd91227e8c8a68ca2b4020b4c6b

also I had a problem with :

/home/ubuntu/starlight/zapps/Escrow/orchestration/common/commitment-storage.mjs on line 234.

connecting to mongo: mongodb://admin:admin@zapp-mongo:27017
error: Cannot read properties of undefined (reading 'preimage') TypeError: Cannot read properties of undefined (reading 'preimage')
    at getInputCommitments (file:///app/orchestration/common/commitment-storage.mjs:234:36)
    at withdraw (file:///app/orchestration/withdraw.mjs:104:6)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async service_withdraw (file:///app/orchestration/api_services.mjs:135:28)

**Comment by MirandaWood** [comment]
This issue is fixed in an upcoming PR, until it's merged paste this into your shield constructor:
`newNullifierRoot = Initial_NullifierRoot;`
Since your tx failed, no commitments will be on-chain and so you will have no commitments in your db. Hope this helps!

**Comment by renankruger** [comment]
tks , what would be the `Initial_NullifierRoot`  value?

**Comment by renankruger** [comment]
found it on MerkleTree.sol

**Comment by MirandaWood** [comment]
It's the root value for an empty nullifier tree, let me know here if all goes through!

**Comment by renankruger** [comment]
https://mumbai.polygonscan.com/tx/0x8004efc72e2651ddc879ceaa417d831e665de7b4360bb079ae8362844bdb7693

**Comment by renankruger** [comment]
Tks, one transfer worked but the second one no. And on /home/ubuntu/starlight/zapps/Escrow/orchestration/common/commitment-storage.mjs the code is expecting always two commitments on line 234

	if (
		parseInt(possibleCommitments[0].preimage.value, 10) +
			parseInt(possibleCommitments[1].preimage.value, 10) >=
		parseInt(value, 10)
	) {
		return [true, possibleCommitments[0], possibleCommitments[1]];
	} else if (commitmentsSum >= parseInt(value, 10))
		return [false, possibleCommitments[0], possibleCommitments[1]];
	return null;

do you know why ?

here is the failed transaction as well!

https://mumbai.polygonscan.com/tx/0x0758cd9ba15ac94e3ad65700b7d0a702e547cc17568dada0abbc1592740f1172

**Comment by renankruger** [comment]
And what about the error on the transaction?

**Comment by MirandaWood** [comment]
Does this transaction not contain enough commitments? If so an error is expected. Otherwise I would need the transaction inputs and what function is being called, which isn't easily extracted from polygonscan. There are many reasons the nullifier root could be out of sync so I'd need more information on that.

**Comment by MirandaWood** [comment]
It would be useful to see the zapp logs for this particular call (from the `zapp` container, or `apiservice` container if you are using APIs) and the zapp log error from the previous failure. The latter is because I'm wondering whether the zapp state has been affected by previous errors. Thank you!

**Comment by renankruger** [comment]
the Utxo for the transfer to another wallet has the same public key?

**Comment by MirandaWood** [comment]
Your logs looks normal to me for this transfer. And yes that's normal, if you don't input a public key it will by default use your own. I think the previous error may have affected the zapp state, which shouldn't happen, do you have details of that error from the zapp?

**Comment by renankruger** [comment]
I will try to find it out!

**Comment by renankruger** [comment]
F',
  blockNumber: 37888050,
  transactionHash: '0x8004efc72e2651ddc879ceaa417d831e665de7b4360bb079ae8362844bdb7693',
  transactionIndex: 9,
  blockHash: '0x757cb98da9e413d2a43402d7f749a89febbda8c2749e5bd209544b14dd122d15',
  logIndex: 18,
  removed: false,
  id: 'log_c3e2b776',
  returnValues: Result {
    '0': '2',
    '1': [
      '15243218930959192431790673692335200729109458915042240579599862912387488858886',
      '17330899646434644337364845942165164361353628945920532841976343530684191568861'
    ],
    '2': '18700846323779560858920748931527134285560841135883412229712394086617469941983',
    minLeafIndex: '2',
    leafValues: [
      '15243218930959192431790673692335200729109458915042240579599862912387488858886',
      '17330899646434644337364845942165164361353628945920532841976343530684191568861'
    ],
    root: '18700846323779560858920748931527134285560841135883412229712394086617469941983'
  },
  event: 'NewLeaves',
  signature: '0x39623a9bbcaf7943af164a1aee0fd809f7101d4d8c7727239dace363779587db',
  raw: {
    data: '0x0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000006029584dce127ded6ef16c8f14be32dafec5d8f25f849614a8528b4bbf9447f8df000000000000000000000000000000000000000000000000000000000000000221b35b2e265f0b6f1555eb08d25af5dd1bf6a6a74a1f3d266145245d876ac3062650f10ba7af491483c48bab4c81832a5f817777ab64d2932317adcf6d8f73dd',
    topics: [
      '0x39623a9bbcaf7943af164a1aee0fd809f7101d4d8c7727239dace363779587db'
    ]
  }
}
Merkle tree event returnValues:
Result {
  '0': '2',
  '1': [
    '15243218930959192431790673692335200729109458915042240579599862912387488858886',
    '17330899646434644337364845942165164361353628945920532841976343530684191568861'
  ],
  '2': '18700846323779560858920748931527134285560841135883412229712394086617469941983',
  minLeafIndex: '2',
  leafValues: [
    '15243218930959192431790673692335200729109458915042240579599862912387488858886',
    '17330899646434644337364845942165164361353628945920532841976343530684191568861'
  ],
  root: '18700846323779560858920748931527134285560841135883412229712394086617469941983'
}
http: 
Calling /start for 'EscrowShield' tree and address '0x167A29Ca0bf0ADf7Be0995b6cCE2E0eEe331097F'
http: Timber Response: filter already started for EscrowShield 
 { message: 'filter already started for EscrowShield' }
info: EscrowShield Address: 0x167A29Ca0bf0ADf7Be0995b6cCE2E0eEe331097F
connecting to mongo: mongodb://admin:admin@zapp-mongo:27017
error: Cannot read properties of undefined (reading 'preimage') TypeError: Cannot read properties of undefined (reading 'preimage')
    at getInputCommitments (file:///app/orchestration/common/commitment-storage.mjs:234:36)
    at withdraw (file:///app/orchestration/withdraw.mjs:104:6)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async service_withdraw (file:///app/orchestration/api_services.mjs:135:28)
http:        
Calling /start for 'EscrowShield' tree and address '0x167A29Ca0bf0ADf7Be0995b6cCE2E0eEe331097F'
http: Timber Response: filter already started for EscrowShield 
 { message: 'filter already started for EscrowShield' }
info: EscrowShield Address: 0x167A29Ca0bf0ADf7Be0995b6cCE2E0eEe331097F
connecting to mongo: mongodb://admin:admin@zapp-mongo:27017
error: Cannot read properties of undefined (reading 'preimage') TypeError: Cannot read properties of undefined (reading 'preimage')
    at getInputCommitments (file:///app/orchestration/common/commitment-storage.mjs:234:36)
    at transfer (file:///app/orchestration/transfer.mjs:110:6)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async service_transfer (file:///app/orchestration/api_services.mjs:93:28)
http: 
Calling /start for 'EscrowShield' tree and address '0x167A29Ca0bf0ADf7Be0995b6cCE2E0eEe331097F'
http: Timber Response: filter already started for EscrowShield 
 { message: 'filter already started for EscrowShield' }
info: EscrowShield Address: 0x167A29Ca0bf0ADf7Be0995b6cCE2E0eEe331097F
connecting to mongo: mongodb://admin:admin@zapp-mongo:27017
error: Cannot read properties of undefined (reading 'preimage') TypeError: Cannot read properties of undefined (reading 'preimage')
    at getInputCommitments (file:///app/orchestration/common/commitment-storage.mjs:234:36)
    at withdraw (file:///app/orchestration/withdraw.mjs:104:6)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async service_withdraw (file:///app/orchestration/api_services.mjs:135:28)
^CShutting down
HTTP server closed.``

**Comment by MirandaWood** [comment]
Ah, did the server close at the very end there?
Currently, as the nullifier tree implementation is quite new, we are holding state in the zapp container, which also acts as the API container. So if you close it then re-open for an existing deployment unfortunately the state becomes misaligned. Sorry this isn't documented very well particularly for testnet deployments where you expect to continue using the same contract addr through multiple runs. 
In the near future we'll add code to either re-instate the nullifiers (since they are stored in the commitments db which isn't closed when the API is) or move to a mongo db for nullifiers.

**Comment by renankruger** [comment]
I modified it to maintan the volumes on the Mongo image, even doing this are there states being stored on the application?

**Comment by renankruger** [comment]
can you explain or show me where to change this behavior to store this data in the mongo database?

**Comment by MirandaWood** [comment]
Hi, so the nullifier tree is _not_ kept in any mongo container. It is kept in js state, which is the issue we will solve in the near future. 
It's not a simple change - it means rewriting any code regarding the nullifier tree in `commitment-storage` to instead use a mongo db. For now, reinstating would be easier and likely what we will start with. Hope that helps!

**Comment by renankruger** [comment]
tks will close this issue, and evaluate changes on 'commitment-storage' on my project.
