### ISSUE TITLE
zokrates-worker-starlight:v0.2 only available to ARM

### ISSUE THREAD

**Issue by thiagodeev** [EYBlockchain/starlight#231]
I'm using an AMD64 linux distribution and I can't run the starlight because the more recent version of this docker image (ghcr.io/eyblockchain/zokrates-worker-starlight:v0.2) only have ARM platform configured.
Please, also host an AMD64 version or provide the original image Dockerfile, so that we can build in our platform.

**Comment by SwatiEY** [comment]
this is the dockerfile for zokrates-woker [https://github.com/EYBlockchain/zokrates-worker/blob/swati/starlight/Dockerfile](url),

I will also update this to have an image for an AMD64 platform
