### ISSUE TITLE
No guarantee that the encrypted value will be decipherable by the receiver

### ISSUE THREAD

**Issue by jimthematrix** [EYBlockchain/starlight#233]
It seems that the recipient's public key that was used to derive the shared secret in ECDH (or kem-dem), does not have to match the actual recipient's public key, because it's a private input.

I think this means that there is no guarantee that the recipient will be able to decrypt the cipher text, after a successful transfer.

On the other hand, I don't have a solution that accomplishes the guarantee without making the receiver's public key as a public input to the proof verification.

**Comment by SwatiEY** [comment]
We register the zkp public keys with the smart contract using the the function registerZKPkeys, and if you get the keys for the recipient from the smart contract, he will be able to decrypt it correctly, there is no need to make it a public input to the circuit. 

you can use this get the keys correctly from the smart contract 
`await this.instance.methods.zkpPublicKeys(recipient.hex(20)).call();`, to the get keys for recipient inside the transfer function. 

you can check the function registerKey in orchestration/common/contract.mjs, this register the keys on the smart contract.
