### ISSUE TITLE
No protection from using existing commitments in the output array

### ISSUE THREAD

**Issue by jimthematrix** [EYBlockchain/starlight#234]
It doesn't look like the generated contracts can prevent the transaction from using an existing commitment as part of the output commitments array.

Each output commitment is supposed to be new, which means they must be proven to not be part of the unspent list of commitments or the spent list.

However in the current implementation, I don't see this check being performed. In fact I don't think this check is possible today because the unspent list is captured by the incremental merkle tree that only supports membership proofs (you can't perform a non-membership proof with this type of trees), and the spent list is captured as a list of nullifiers.

**Comment by SwatiEY** [comment]
We have added the sparse-merkle tree to store the commitments inside of a list, which have a non-membership proof as well. So this is not a problem any more.
