### ISSUE TITLE
Fix error when a contract uses structs that are non-secret global variables that interact with secret variables and when local structs are used.

### ISSUE THREAD

**Issue by lydiagarms** [EYBlockchain/starlight#265]
Use SimpleStruct5 to test.

Also fix errors in SimpleStruct2

In add.mjs lines 92, 93, 103, 104 - attempting to use myrct.tax/amount as a general number before it has been generalised
Line 121 error: Attempting to 'convert' something other than an object/array: undefined Error: Attempting to 'convert' something other than an object/array: undefined.

**Comment by Westlad** [comment]
PR merged
