### ISSUE TITLE
"timber_mongo" does not exist under owner "eyblockchain/timber-mongo"

### ISSUE THREAD

**Issue by zhzhang666** [EYBlockchain/starlight#38]
Hello, when running trusted setups on all circuit files: by "./bin/setup", the following error happens, how can I solve this problem?

Pulling timber-mongo (docker.pkg.github.com/eyblockchain/timber-mongo/timber_mongo:73c12fc8bd35d4cab739c836b738b416f6db64ba)...
ERROR: repository docker.pkg.github.com/eyblockchain/timber-mongo/timber_mongo not found: name unknown: docker package "timber_mongo" does not exist under owner "eyblockchain/timber-mongo"

**Comment by MirandaWood** [comment]
Hello, I have recently changed the code to use a local build of timber-mongo, so it no longer pulls from `docker.pkg.github.com/eyblockchain`. If you pull the changes from master and re-zappify the contract does it work?

**Comment by zhzhang666** [comment]
Yes, after updating the code, it works. Thank you very much!
