### ISSUE TITLE
Permissioned assignment of a secret global variable

### ISSUE THREAD

**Issue by iAmMichaelConnor** [EYBlockchain/starlight#4]
There are 2 scenarios to consider:

```solidity
secret uint a;
address owner; // _publicly visible_ owner address

function assign(secret uint value) {
    require(msg.sender == owner, "Not permitted to edit this state");
    a = value;
}
```

The second scenario is tricker, and might require us to 'guess' the developer's intentions (make decisions for them), because if the `owner` address is `secret`, then how is it instantiated? It's a similar problem to issue #3, where instantiating a variable was different from editing it thereafter.

```
secret uint a;
secret address owner; // _secret_ owner address

function assign(secret uint value) {
    require(msg.sender == owner, "Not permitted to edit this state");
    a = value;
}
```

**Comment by MirandaWood** [comment]
My work on this will be adding secret addresses and treating them as an accessed state when ownership must be proven
