### ISSUE TITLE
Some compiled Shield contracts have stack too deep error

### ISSUE THREAD

**Issue by MirandaWood** [EYBlockchain/starlight#40]
While adding some more complex contracts, I found that the largest ones suffer from a stack too deep error when compiling the Shield contract (usually in the verify function).
E.g. `test/contracts/Partitioned-decrement-2.zol` requires a lot of heavy commitment logic and accessed states (which means sometimes we need to check nullifiers don't exist _without_ adding them, requiring extra logic in the shield)

Possible solutions:

- Abstract out some shield functionality (e.g. checking nullifiers, constructing public input arrays)
- Remove intermediate variables (e.g. `uint[] memory newNullifiers = _inputs.newNullifiers;`)

For now, I'm leaving the offending test contract in master because it still produces a working zApp and demonstrates complex but correct code throughout. The tests can be run by removing some variables from the shield too.

**Comment by MirandaWood** [comment]
Since we have switched to Groth16 as the default, we have a much lighter verify function, so this issue may not be relevant. Needs confirmation!

**Comment by dwebchapey** [comment]
Closing comment :
Shield contracts for both ` Partitioned-decrement-2.zol` and `test/error-checks/Public-accessed.zol` are getting compiled. Therefore, this issue can be considered resolved for now. I have moved `test/error-checks/Public-accessed.zol` to `test/contracts/Public-accessed-2.zol` as part of PR #93 .
